name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 767397888174.dkr.ecr.eu-west-2.amazonaws.com

    - name: Build docker image
      run: docker build -t app .

    - name: Tag docker image
      run: docker tag app:latest 767397888174.dkr.ecr.eu-west-2.amazonaws.com/app:latest

    - name: Push docker image
      run: docker push 767397888174.dkr.ecr.eu-west-2.amazonaws.com/app:latest

    - name: Deploy Lambda Function
      run: aws lambda update-function-code --function-name app --image-uri 767397888174.dkr.ecr.eu-west-2.amazonaws.com/app:latest
